{
 "title": "consommation électrique",
 "time": { "from": "now/d", "to": "now-1m" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Mesure intervalle de temps absolu (kWh)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "firstDay =  from(bucket: \"conso\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r[\"_measurement\"] == \"mesure_float\")\n|> filter(fn: (r) => r[\"_field\"] == \"value\")\n|> filter(fn: (r) => r[\"host\"] == \"aad92904f5e0\")\n|> filter(fn: (r) => r[\"topic\"] == \"shellies/shellyem-485519C9F56D/emeter/0/total\")\n|> map(fn: (r) => ({r with _value: r._value * 0.001}))\n|> first()\n//|> yield(name: \"firstDay\") \n\n\n\n\nlastDay = from(bucket: \"conso\")\n|> range(start: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"mesure_float\")\n|> filter(fn: (r) => r[\"_field\"] == \"value\")\n|> filter(fn: (r) => r[\"host\"] == \"aad92904f5e0\")\n|> filter(fn: (r) => r[\"topic\"] == \"shellies/shellyem-485519C9F56D/emeter/0/total\")\n|> map(fn: (r) => ({r with _value: r._value * 0.001 }))\n|> first()\n//|> yield(name: \"lastDay\") \n\n\n//overview = union(tables: [firstDay, lastDay])\n//|> difference()\n//overview\n\n//firstDayValue = firstDay\n//|> findRecord(fn: (key) => key._field == \"value\", idx: 0)\n\n//lastDayValue = lastDay\n//|> findRecord(fn: (key) => key._field == \"value\", idx: 0)\n\n//lastDay\n//|> map(fn: (r) => ({r with _value: r._value * 0.001 / 60.0}))\n//|> map(fn: (r) => ({ r with difference: 100.00 - 50.00}))\n\njoin_datasteams = join(\n    tables: {firstDay: firstDay, lastDay: lastDay},\n    on: [\"_field\"], method: \"inner\")\n|> map(fn: (r) => ({ r with _value: (r._value_lastDay - r._value_firstDay)}))\n|> keep(columns: [\"_value\", \"host\"])\n|> yield(name: \"resultat\") \n\n//join_datasteams\n"
    }
   ]
  },
  {
   "title": "Tarifs",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 0 },
   "options": {
    "content": "Au 01/07/22\nhttps://particuliers.engie.fr/content/dam/pdf/fiches-descriptives/fiche-descriptive-elec-reference.pdf\n1kWh = 0,25934 EUR"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  odometer\nFROM positions\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tarif intervalle de temps absolu (EUR)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "//tarif = '0.25934'\n\nfirstDay =  from(bucket: \"conso\")\n|> range(start: v.timeRangeStart)\n|> filter(fn: (r) => r[\"_measurement\"] == \"mesure_float\")\n|> filter(fn: (r) => r[\"_field\"] == \"value\")\n|> filter(fn: (r) => r[\"host\"] == \"aad92904f5e0\")\n|> filter(fn: (r) => r[\"topic\"] == \"shellies/shellyem-485519C9F56D/emeter/0/total\")\n|> map(fn: (r) => ({r with _value: r._value * 0.001}))\n|> first()\n//|> yield(name: \"firstDay\") \n\n\n\n\nlastDay = from(bucket: \"conso\")\n|> range(start: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"mesure_float\")\n|> filter(fn: (r) => r[\"_field\"] == \"value\")\n|> filter(fn: (r) => r[\"host\"] == \"aad92904f5e0\")\n|> filter(fn: (r) => r[\"topic\"] == \"shellies/shellyem-485519C9F56D/emeter/0/total\")\n|> map(fn: (r) => ({r with _value: r._value * 0.001 }))\n|> first()\n//|> yield(name: \"lastDay\") \n\n\n//overview = union(tables: [firstDay, lastDay])\n//|> difference()\n//overview\n\n//firstDayValue = firstDay\n//|> findRecord(fn: (key) => key._field == \"value\", idx: 0)\n\n//lastDayValue = lastDay\n//|> findRecord(fn: (key) => key._field == \"value\", idx: 0)\n\n//lastDay\n//|> map(fn: (r) => ({r with _value: r._value * 0.001 / 60.0}))\n//|> map(fn: (r) => ({ r with difference: 100.00 - 50.00}))\n\njoin_datasteams = join(\n    tables: {firstDay: firstDay, lastDay: lastDay},\n    on: [\"_field\"], method: \"inner\")\n|> map(fn: (r) => ({ r with _value: (r._value_lastDay - r._value_firstDay)  * 0.25934 }))\n|> keep(columns: [\"_value\", \"host\"])\n|> yield(name: \"resultat\") \n\n//join_datasteams\n"
    }
   ]
  },
  {
   "title": "Mesure énergie cumulative (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "  from(bucket: \"conso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesure_float\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"aad92904f5e0\")\n  |> filter(fn: (r) => r[\"topic\"] == \"shellies/shellyem-485519C9F56D/emeter/0/total\")\n    |> map(fn: (r) => ({r with _value: r._value * 0.001 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Puissance active instantanée (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"conso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesure_float\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"aad92904f5e0\")\n  |> filter(fn: (r) => r[\"topic\"] == \"shellies/shellyem-485519C9F56D/emeter/0/energy\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tension (V)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"conso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesure_float\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"aad92904f5e0\")\n  |> filter(fn: (r) => r[\"topic\"] == \"shellies/shellyem-485519C9F56D/emeter/0/voltage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}